name: Security check - Bandit

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2

    - name: Security check - Bandit
      uses: Joel-hanson/bandit-report-artifacts@V1
      with:
        python_version: ${{ matrix.python-version }}
        project_path: .
        ignore_failure: false

    - name: Security check report artifacts
      uses: actions/upload-artifact@v1
      # if: failure()
      with:
        name: Security report
        path: output/security_report.txt
